### ISSUE TITLE
babylon.yaml generated in wrong directory (should go into subfolder)

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/babylon#94]
![image](https://user-images.githubusercontent.com/3196313/71625491-1aafea00-2bb6-11ea-99b6-8aee5936240d.png)

the babylon.yaml file is copied from the executing directory (good), but dumped into the original dir where the model exists. This behavior is incorrect, we need it to be in the subfolder where the model is run, as that should contain the record of the settings used during execution. Likewise, the current behavior will cause clashes when multiple runs are submitted from the same directory

**Comment by shairozan** [comment]
We're dropping a json file into the output directories now, but it's not in the code to actually try loading it. The closest we get is the original model directory. Do we want to change this such that we try to re-load the configuration once we have a model establish from the arguments? Or maybe go back and re-implement the --config flag such that we just load it immediately (as json) during startup.

**Comment by dpastoor** [comment]
Hmm good point I forgot about that. Yes having a config flag makes sense regardless and we can provide a path to either ../Babylon.yml if nothing was set or provide the user defined one.

I see the config json evolving still to both have more info and not 1:1 represent the entire Babylon config but instead the relevant parts to that specific model run

**Comment by shairozan** [comment]
It also brings up some other considerations. What we're writing into the output directory now is a full dump of the NonMemModel including the Configuration object (Which is marshalled into it from Viper). 

For the rest of the application, we're using built-in viper functionality to load a file (if none is loaded etc) but it won't be able to read this as the keys won't make sense. What we may have to do to keep things sane is to write an implementation for io.Reader since viper.ReadConfig() takes one. That method could extract only the configuration, re-render it to string, then bytes and then hand it off to viper

**Comment by shairozan** [comment]
We've updated the application since this discussion to write the babylon.yaml into the output (to facilitate re-execution) but we also have the json file which contains additional metadata.
